using System.Collections.Generic;
using UnityEngine;


namespace Dono.MidiConnectionForUnity
{
    public partial class ChannelMultiSwitcher //: MidiDevice
    {
        private static int maxPorts = 128;
        [SerializeField] private byte[] channelToOutPort = new byte[16];
        [SerializeField] private byte portCount = 0;

        [SerializeField] private List<MidiDevice> outPorts0 = new List<MidiDevice>();
        [SerializeField] private List<MidiDevice> outPorts1 = new List<MidiDevice>();
        [SerializeField] private List<MidiDevice> outPorts2 = new List<MidiDevice>();
        [SerializeField] private List<MidiDevice> outPorts3 = new List<MidiDevice>();
        [SerializeField] private List<MidiDevice> outPorts4 = new List<MidiDevice>();
        [SerializeField] private List<MidiDevice> outPorts5 = new List<MidiDevice>();
        [SerializeField] private List<MidiDevice> outPorts6 = new List<MidiDevice>();
        [SerializeField] private List<MidiDevice> outPorts7 = new List<MidiDevice>();
        [SerializeField] private List<MidiDevice> outPorts8 = new List<MidiDevice>();
        [SerializeField] private List<MidiDevice> outPorts9 = new List<MidiDevice>();
        [SerializeField] private List<MidiDevice> outPorts10 = new List<MidiDevice>();
        [SerializeField] private List<MidiDevice> outPorts11 = new List<MidiDevice>();
        [SerializeField] private List<MidiDevice> outPorts12 = new List<MidiDevice>();
        [SerializeField] private List<MidiDevice> outPorts13 = new List<MidiDevice>();
        [SerializeField] private List<MidiDevice> outPorts14 = new List<MidiDevice>();
        [SerializeField] private List<MidiDevice> outPorts15 = new List<MidiDevice>();
        [SerializeField] private List<MidiDevice> outPorts16 = new List<MidiDevice>();
        [SerializeField] private List<MidiDevice> outPorts17 = new List<MidiDevice>();
        [SerializeField] private List<MidiDevice> outPorts18 = new List<MidiDevice>();
        [SerializeField] private List<MidiDevice> outPorts19 = new List<MidiDevice>();
        [SerializeField] private List<MidiDevice> outPorts20 = new List<MidiDevice>();
        [SerializeField] private List<MidiDevice> outPorts21 = new List<MidiDevice>();
        [SerializeField] private List<MidiDevice> outPorts22 = new List<MidiDevice>();
        [SerializeField] private List<MidiDevice> outPorts23 = new List<MidiDevice>();
        [SerializeField] private List<MidiDevice> outPorts24 = new List<MidiDevice>();
        [SerializeField] private List<MidiDevice> outPorts25 = new List<MidiDevice>();
        [SerializeField] private List<MidiDevice> outPorts26 = new List<MidiDevice>();
        [SerializeField] private List<MidiDevice> outPorts27 = new List<MidiDevice>();
        [SerializeField] private List<MidiDevice> outPorts28 = new List<MidiDevice>();
        [SerializeField] private List<MidiDevice> outPorts29 = new List<MidiDevice>();
        [SerializeField] private List<MidiDevice> outPorts30 = new List<MidiDevice>();
        [SerializeField] private List<MidiDevice> outPorts31 = new List<MidiDevice>();
        [SerializeField] private List<MidiDevice> outPorts32 = new List<MidiDevice>();
        [SerializeField] private List<MidiDevice> outPorts33 = new List<MidiDevice>();
        [SerializeField] private List<MidiDevice> outPorts34 = new List<MidiDevice>();
        [SerializeField] private List<MidiDevice> outPorts35 = new List<MidiDevice>();
        [SerializeField] private List<MidiDevice> outPorts36 = new List<MidiDevice>();
        [SerializeField] private List<MidiDevice> outPorts37 = new List<MidiDevice>();
        [SerializeField] private List<MidiDevice> outPorts38 = new List<MidiDevice>();
        [SerializeField] private List<MidiDevice> outPorts39 = new List<MidiDevice>();
        [SerializeField] private List<MidiDevice> outPorts40 = new List<MidiDevice>();
        [SerializeField] private List<MidiDevice> outPorts41 = new List<MidiDevice>();
        [SerializeField] private List<MidiDevice> outPorts42 = new List<MidiDevice>();
        [SerializeField] private List<MidiDevice> outPorts43 = new List<MidiDevice>();
        [SerializeField] private List<MidiDevice> outPorts44 = new List<MidiDevice>();
        [SerializeField] private List<MidiDevice> outPorts45 = new List<MidiDevice>();
        [SerializeField] private List<MidiDevice> outPorts46 = new List<MidiDevice>();
        [SerializeField] private List<MidiDevice> outPorts47 = new List<MidiDevice>();
        [SerializeField] private List<MidiDevice> outPorts48 = new List<MidiDevice>();
        [SerializeField] private List<MidiDevice> outPorts49 = new List<MidiDevice>();
        [SerializeField] private List<MidiDevice> outPorts50 = new List<MidiDevice>();
        [SerializeField] private List<MidiDevice> outPorts51 = new List<MidiDevice>();
        [SerializeField] private List<MidiDevice> outPorts52 = new List<MidiDevice>();
        [SerializeField] private List<MidiDevice> outPorts53 = new List<MidiDevice>();
        [SerializeField] private List<MidiDevice> outPorts54 = new List<MidiDevice>();
        [SerializeField] private List<MidiDevice> outPorts55 = new List<MidiDevice>();
        [SerializeField] private List<MidiDevice> outPorts56 = new List<MidiDevice>();
        [SerializeField] private List<MidiDevice> outPorts57 = new List<MidiDevice>();
        [SerializeField] private List<MidiDevice> outPorts58 = new List<MidiDevice>();
        [SerializeField] private List<MidiDevice> outPorts59 = new List<MidiDevice>();
        [SerializeField] private List<MidiDevice> outPorts60 = new List<MidiDevice>();
        [SerializeField] private List<MidiDevice> outPorts61 = new List<MidiDevice>();
        [SerializeField] private List<MidiDevice> outPorts62 = new List<MidiDevice>();
        [SerializeField] private List<MidiDevice> outPorts63 = new List<MidiDevice>();
        [SerializeField] private List<MidiDevice> outPorts64 = new List<MidiDevice>();
        [SerializeField] private List<MidiDevice> outPorts65 = new List<MidiDevice>();
        [SerializeField] private List<MidiDevice> outPorts66 = new List<MidiDevice>();
        [SerializeField] private List<MidiDevice> outPorts67 = new List<MidiDevice>();
        [SerializeField] private List<MidiDevice> outPorts68 = new List<MidiDevice>();
        [SerializeField] private List<MidiDevice> outPorts69 = new List<MidiDevice>();
        [SerializeField] private List<MidiDevice> outPorts70 = new List<MidiDevice>();
        [SerializeField] private List<MidiDevice> outPorts71 = new List<MidiDevice>();
        [SerializeField] private List<MidiDevice> outPorts72 = new List<MidiDevice>();
        [SerializeField] private List<MidiDevice> outPorts73 = new List<MidiDevice>();
        [SerializeField] private List<MidiDevice> outPorts74 = new List<MidiDevice>();
        [SerializeField] private List<MidiDevice> outPorts75 = new List<MidiDevice>();
        [SerializeField] private List<MidiDevice> outPorts76 = new List<MidiDevice>();
        [SerializeField] private List<MidiDevice> outPorts77 = new List<MidiDevice>();
        [SerializeField] private List<MidiDevice> outPorts78 = new List<MidiDevice>();
        [SerializeField] private List<MidiDevice> outPorts79 = new List<MidiDevice>();
        [SerializeField] private List<MidiDevice> outPorts80 = new List<MidiDevice>();
        [SerializeField] private List<MidiDevice> outPorts81 = new List<MidiDevice>();
        [SerializeField] private List<MidiDevice> outPorts82 = new List<MidiDevice>();
        [SerializeField] private List<MidiDevice> outPorts83 = new List<MidiDevice>();
        [SerializeField] private List<MidiDevice> outPorts84 = new List<MidiDevice>();
        [SerializeField] private List<MidiDevice> outPorts85 = new List<MidiDevice>();
        [SerializeField] private List<MidiDevice> outPorts86 = new List<MidiDevice>();
        [SerializeField] private List<MidiDevice> outPorts87 = new List<MidiDevice>();
        [SerializeField] private List<MidiDevice> outPorts88 = new List<MidiDevice>();
        [SerializeField] private List<MidiDevice> outPorts89 = new List<MidiDevice>();
        [SerializeField] private List<MidiDevice> outPorts90 = new List<MidiDevice>();
        [SerializeField] private List<MidiDevice> outPorts91 = new List<MidiDevice>();
        [SerializeField] private List<MidiDevice> outPorts92 = new List<MidiDevice>();
        [SerializeField] private List<MidiDevice> outPorts93 = new List<MidiDevice>();
        [SerializeField] private List<MidiDevice> outPorts94 = new List<MidiDevice>();
        [SerializeField] private List<MidiDevice> outPorts95 = new List<MidiDevice>();
        [SerializeField] private List<MidiDevice> outPorts96 = new List<MidiDevice>();
        [SerializeField] private List<MidiDevice> outPorts97 = new List<MidiDevice>();
        [SerializeField] private List<MidiDevice> outPorts98 = new List<MidiDevice>();
        [SerializeField] private List<MidiDevice> outPorts99 = new List<MidiDevice>();
        [SerializeField] private List<MidiDevice> outPorts100 = new List<MidiDevice>();
        [SerializeField] private List<MidiDevice> outPorts101 = new List<MidiDevice>();
        [SerializeField] private List<MidiDevice> outPorts102 = new List<MidiDevice>();
        [SerializeField] private List<MidiDevice> outPorts103 = new List<MidiDevice>();
        [SerializeField] private List<MidiDevice> outPorts104 = new List<MidiDevice>();
        [SerializeField] private List<MidiDevice> outPorts105 = new List<MidiDevice>();
        [SerializeField] private List<MidiDevice> outPorts106 = new List<MidiDevice>();
        [SerializeField] private List<MidiDevice> outPorts107 = new List<MidiDevice>();
        [SerializeField] private List<MidiDevice> outPorts108 = new List<MidiDevice>();
        [SerializeField] private List<MidiDevice> outPorts109 = new List<MidiDevice>();
        [SerializeField] private List<MidiDevice> outPorts110 = new List<MidiDevice>();
        [SerializeField] private List<MidiDevice> outPorts111 = new List<MidiDevice>();
        [SerializeField] private List<MidiDevice> outPorts112 = new List<MidiDevice>();
        [SerializeField] private List<MidiDevice> outPorts113 = new List<MidiDevice>();
        [SerializeField] private List<MidiDevice> outPorts114 = new List<MidiDevice>();
        [SerializeField] private List<MidiDevice> outPorts115 = new List<MidiDevice>();
        [SerializeField] private List<MidiDevice> outPorts116 = new List<MidiDevice>();
        [SerializeField] private List<MidiDevice> outPorts117 = new List<MidiDevice>();
        [SerializeField] private List<MidiDevice> outPorts118 = new List<MidiDevice>();
        [SerializeField] private List<MidiDevice> outPorts119 = new List<MidiDevice>();
        [SerializeField] private List<MidiDevice> outPorts120 = new List<MidiDevice>();
        [SerializeField] private List<MidiDevice> outPorts121 = new List<MidiDevice>();
        [SerializeField] private List<MidiDevice> outPorts122 = new List<MidiDevice>();
        [SerializeField] private List<MidiDevice> outPorts123 = new List<MidiDevice>();
        [SerializeField] private List<MidiDevice> outPorts124 = new List<MidiDevice>();
        [SerializeField] private List<MidiDevice> outPorts125 = new List<MidiDevice>();
        [SerializeField] private List<MidiDevice> outPorts126 = new List<MidiDevice>();
        [SerializeField] private List<MidiDevice> outPorts127 = new List<MidiDevice>();

        public byte GetOutPortNumber(byte channel) => channelToOutPort[channel];
        private List<MidiDevice> outPorts(int val)
        {
            switch (val)
            {
                case 0: return outPorts0;
                case 1: return outPorts1;
                case 2: return outPorts2;
                case 3: return outPorts3;
                case 4: return outPorts4;
                case 5: return outPorts5;
                case 6: return outPorts6;
                case 7: return outPorts7;
                case 8: return outPorts8;
                case 9: return outPorts9;
                case 10: return outPorts10;
                case 11: return outPorts11;
                case 12: return outPorts12;
                case 13: return outPorts13;
                case 14: return outPorts14;
                case 15: return outPorts15;
                case 16: return outPorts16;
                case 17: return outPorts17;
                case 18: return outPorts18;
                case 19: return outPorts19;
                case 20: return outPorts20;
                case 21: return outPorts21;
                case 22: return outPorts22;
                case 23: return outPorts23;
                case 24: return outPorts24;
                case 25: return outPorts25;
                case 26: return outPorts26;
                case 27: return outPorts27;
                case 28: return outPorts28;
                case 29: return outPorts29;
                case 30: return outPorts30;
                case 31: return outPorts31;
                case 32: return outPorts32;
                case 33: return outPorts33;
                case 34: return outPorts34;
                case 35: return outPorts35;
                case 36: return outPorts36;
                case 37: return outPorts37;
                case 38: return outPorts38;
                case 39: return outPorts39;
                case 40: return outPorts40;
                case 41: return outPorts41;
                case 42: return outPorts42;
                case 43: return outPorts43;
                case 44: return outPorts44;
                case 45: return outPorts45;
                case 46: return outPorts46;
                case 47: return outPorts47;
                case 48: return outPorts48;
                case 49: return outPorts49;
                case 50: return outPorts50;
                case 51: return outPorts51;
                case 52: return outPorts52;
                case 53: return outPorts53;
                case 54: return outPorts54;
                case 55: return outPorts55;
                case 56: return outPorts56;
                case 57: return outPorts57;
                case 58: return outPorts58;
                case 59: return outPorts59;
                case 60: return outPorts60;
                case 61: return outPorts61;
                case 62: return outPorts62;
                case 63: return outPorts63;
                case 64: return outPorts64;
                case 65: return outPorts65;
                case 66: return outPorts66;
                case 67: return outPorts67;
                case 68: return outPorts68;
                case 69: return outPorts69;
                case 70: return outPorts70;
                case 71: return outPorts71;
                case 72: return outPorts72;
                case 73: return outPorts73;
                case 74: return outPorts74;
                case 75: return outPorts75;
                case 76: return outPorts76;
                case 77: return outPorts77;
                case 78: return outPorts78;
                case 79: return outPorts79;
                case 80: return outPorts80;
                case 81: return outPorts81;
                case 82: return outPorts82;
                case 83: return outPorts83;
                case 84: return outPorts84;
                case 85: return outPorts85;
                case 86: return outPorts86;
                case 87: return outPorts87;
                case 88: return outPorts88;
                case 89: return outPorts89;
                case 90: return outPorts90;
                case 91: return outPorts91;
                case 92: return outPorts92;
                case 93: return outPorts93;
                case 94: return outPorts94;
                case 95: return outPorts95;
                case 96: return outPorts96;
                case 97: return outPorts97;
                case 98: return outPorts98;
                case 99: return outPorts99;
                case 100: return outPorts100;
                case 101: return outPorts101;
                case 102: return outPorts102;
                case 103: return outPorts103;
                case 104: return outPorts104;
                case 105: return outPorts105;
                case 106: return outPorts106;
                case 107: return outPorts107;
                case 108: return outPorts108;
                case 109: return outPorts109;
                case 110: return outPorts110;
                case 111: return outPorts111;
                case 112: return outPorts112;
                case 113: return outPorts113;
                case 114: return outPorts114;
                case 115: return outPorts115;
                case 116: return outPorts116;
                case 117: return outPorts117;
                case 118: return outPorts118;
                case 119: return outPorts119;
                case 120: return outPorts120;
                case 121: return outPorts121;
                case 122: return outPorts122;
                case 123: return outPorts123;
                case 124: return outPorts124;
                case 125: return outPorts125;
                case 126: return outPorts126;
                case 127: return outPorts127;

                default: return null;
            }
        }
    }
}